### ISSUE TITLE
Tagging user with emote names

### ISSUE THREAD

**Issue by MagmazFX** [Aayzie/forsens-giftbox-lidl-extension#2]
Hey, first of all nice job on the extension, it's really nice to be able to see twitch emotes on other YT channels too now.

I noticed a user trying to respond to someone who had an emote as name which broke the YT comment section tagging.
![image](https://user-images.githubusercontent.com/97740679/149520535-9da244b7-7f71-4327-89db-54f9768ae687.png)

Nothing important really, I don't think it really needs to be fixed either, but I thought I'd let you know in case no one mentioned/noticed it before.

**Comment by Aayzie** [comment]
Ah yep, I do think that should be fixed lol, I just never really had time
yet, but I'll get to fixing it soon.
Thank you!

**Comment by Aayzie** [comment]
This should be fixed now in 1.6.2. Let me know if you encounter any more issues with the extension.
Thanks for the report!
